# Generated by Django 3.2.4 on 2021-08-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210813_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicModel',
        ),
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
