# Generated by Django 3.2.4 on 2021-08-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210815_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8)),
                ('target_id', models.BigIntegerField()),
            ],
        ),
    ]
